### ISSUE TITLE
getting error when running rspec

### ISSUE THREAD

**Issue by eyalgo** [waterlink/rspec-json_expectations#15]
Hi,
I've added  gem 'rspec-json_expectations' to Gemfile.
Then, when I run bundle exec rspec, I get the following error:
```/Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-json_expectations-1.2.1/lib/rspec/json_expectations.rb:1:in `require': cannot load such file -- rspec (LoadError)
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-json_expectations-1.2.1/lib/rspec/json_expectations.rb:1:in `<top (required)>'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `require'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `rescue in block in require'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:68:in `block in require'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /Users/eyalgo/dev/datalift-management-ruby/config/application.rb:17:in `<top (required)>'
	from /Users/eyalgo/dev/datalift-management-ruby/config/environment.rb:2:in `require'
	from /Users/eyalgo/dev/datalift-management-ruby/config/environment.rb:2:in `<top (required)>'
	from /Users/eyalgo/dev/datalift-management-ruby/spec/spec_helper.rb:19:in `require'
	from /Users/eyalgo/dev/datalift-management-ruby/spec/spec_helper.rb:19:in `<top (required)>'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `require'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `block in requires='
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `each'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `requires='
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:103:in `block in process_options_into'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:102:in `each'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:102:in `process_options_into'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:22:in `configure'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:95:in `setup'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
	from /Users/eyalgo/.rbenv/versions/2.3.0/bin/rspec:23:in `load'
	from /Users/eyalgo/.rbenv/versions/2.3.0/bin/rspec:23:in `<main>'```

from Gemfile.lock: rspec-core (3.1.7)

It's even before I even touched spec_helper.rb (that's the only file we use)

Any idea?

**Comment by benoittgt** [comment]
Very strange behavior. What's happen if you specify a rspec file like `bundle exec rspec spec/models/user_spec.rb` ?

**Comment by eyalgo** [comment]
Same thing.
```bundle exec rspec spec/models/facebook_campaign_spec.rb```

```/Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-json_expectations-1.2.1/lib/rspec/json_expectations.rb:1:in `require': cannot load such file -- rspec (LoadError)
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-json_expectations-1.2.1/lib/rspec/json_expectations.rb:1:in `<top (required)>'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `require'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `rescue in block in require'
	from /Users/eyalgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:68:in `block in require'
...```

**Comment by benoittgt** [comment]
Nothing change when you try this ? http://stackoverflow.com/a/25804049/2747638

**Comment by benoittgt** [comment]
And also check : https://github.com/nviennot/irb-config/issues/15

**Comment by eyalgo** [comment]
OK.
so this: https://github.com/nviennot/irb-config/issues/15 helped.
I moved rspec-rails to development and test group.
And also added gem 'rspec' to this group.

Thanks! (closing)
