### ISSUE TITLE
Support all aliased RSpec expectations

### ISSUE THREAD

**Issue by franklinyu** [waterlink/rspec-json_expectations#18]
[RSpec expectation is supported](https://www.relishapp.com/waterlink/rspec-json-expectations/docs/json-expectations/rspec-matcher-support-for-include-json-matcher), but not all their aliases:

``` ruby
require 'rspec/json_expectations'

describe 'sample' do
  it 'passes with original matcher' do
    json = '{"foo":"bar"}'
    expect(json).to include_json(
      foo: be_a_kind_of(String)
    )
  end

  it 'should have succeeded' do
    expect('bar').to a_kind_of(String)
  end

  it 'fails' do
    json = '{"foo":"bar"}'
    expect(json).to include_json(
      foo: a_kind_of(String)
    )
  end
end
```

Here `a_kind_of` is an alias of [`be_a_kind_of`](http://www.rubydoc.info/gems/rspec-expectations/RSpec/Matchers#be_a_kind_of-instance_method). I find the noun-phrase aliases fit better here. Notably `be_kind_of`, another alias of `be_a_kind_of`, is supported. Any reason to reject the noun-phrase?

**Comment by JanStevens** [comment]
Also finding this a bit annoying, small hack around it

In `json_traverser.rb`

```
12: RSPECMATCHERS = defined?(RSpec::Matchers) ? [RSpec::Matchers::BuiltIn::BaseMatcher, RSpec::Matchers::AliasedMatcher] : []
99: return nil unless expected.is_a?(RSpec::Matchers::BuiltIn::BaseMatcher) ||
            expected.is_a?(RSpec::Matchers::AliasedMatcher)
```

Seems to work fine now
