### ISSUE TITLE
Cannot deal with nil in values

### ISSUE THREAD

**Issue by sheerun** [waterlink/rspec-json_expectations#8]
Following fails:

```
expect(phone: nil).to include_json(phone: nil)
```

NotImplementedError:  expectation is not supported
from /Users/sheerun/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-json_expectations-1.1.0/lib/rspec/json_expectations/json_traverser.rb:80:in `handle_unsupported'

**Comment by waterlink** [comment]
Thx for the catch!
